#include "stdafx.h"
#include "Countrylist.h"

const char *countryList[][2] = {
	_T("004"),_T("Afghanistan"),
	_T("008"),_T("Albania, People's Socialist Republic of"),
	_T("010"),_T("Antarctica (the territory South of 60 deg S)"),
	_T("012"),_T("Algeria, People's Democratic Republic of"),
	_T("016"),_T("American Samoa"),
	_T("020"),_T("Andorra, Principality of"),
	_T("024"),_T("Angola, Republic of"),
	_T("028"),_T("Antigua and Barbuda"),
	_T("031"),_T("Azerbaijan, Republic of"),
	_T("032"),_T("Argentina, Argentine Republic"),
	_T("036"),_T("Australia, Commonwealth of"),
	_T("040"),_T("Austria, Republic of"),
	_T("044"),_T("Bahamas, Commonwealth of the"),
	_T("048"),_T("Bahrain, Kingdom of"),
	_T("050"),_T("Bangladesh, People's Republic of"),
	_T("051"),_T("Armenia"),
	_T("052"),_T("Barbados"),
	_T("056"),_T("Belgium, Kingdom of"),
	_T("060"),_T("Bermuda"),
	_T("064"),_T("Bhutan, Kingdom of"),
	_T("068"),_T("Bolivia, Republic of"),
	_T("070"),_T("Bosnia and Herzegovina"),
	_T("072"),_T("Botswana, Republic of"),
	_T("074"),_T("Bouvet Island (Bouvetoya)"),
	_T("076"),_T("Brazil, Federative Republic of"),
	_T("084"),_T("Belize"),
	_T("086"),_T("British Indian Ocean Territory (Chagos Archipelago)"),
	_T("090"),_T("Solomon Islands"),
	_T("092"),_T("British Virgin Islands"),
	_T("096"),_T("Brunei Darussalam"),
	_T("100"),_T("Bulgaria, People's Republic of"),
	_T("104"),_T("Myanmar"),
	_T("108"),_T("Burundi, Republic of"),
	_T("112"),_T("Belarus"),
	_T("116"),_T("Cambodia, Kingdom of"),
	_T("120"),_T("Cameroon, United Republic of"),
	_T("124"),_T("Canada"),
	_T("132"),_T("Cape Verde, Republic of"),
	_T("136"),_T("Cayman Islands"),
	_T("140"),_T("Central African Republic"),
	_T("144"),_T("Sri Lanka, Democratic Socialist Republic of"),
	_T("148"),_T("Chad, Republic of"),
	_T("152"),_T("Chile, Republic of"),
	_T("156"),_T("China, People's Republic of"),
	_T("158"),_T("Taiwan, Province of China"),
	_T("162"),_T("Christmas Island"),
	_T("166"),_T("Cocos (Keeling) Islands"),
	_T("170"),_T("Colombia, Republic of"),
	_T("174"),_T("Comoros, Union of the"),
	_T("175"),_T("Mayotte"),
	_T("178"),_T("Congo, People's Republic of"),
	_T("180"),_T("Congo, Democratic Republic of"),
	_T("184"),_T("Cook Islands"),
	_T("188"),_T("Costa Rica, Republic of"),
	_T("191"),_T("Hrvatska (Croatia)"),
	_T("192"),_T("Cuba, Republic of"),
	_T("196"),_T("Cyprus, Republic of"),
	_T("203"),_T("Czech Republic"),
	_T("204"),_T("Benin, People's Republic of"),
	_T("208"),_T("Denmark, Kingdom of"),
	_T("212"),_T("Dominica, Commonwealth of"),
	_T("214"),_T("Dominican Republic"),
	_T("218"),_T("Ecuador, Republic of"),
	_T("222"),_T("El Salvador, Republic of"),
	_T("226"),_T("Equatorial Guinea, Republic of"),
	_T("231"),_T("Ethiopia"),
	_T("232"),_T("Eritrea"),
	_T("233"),_T("Estonia"),
	_T("234"),_T("Faeroe Islands"),
	_T("238"),_T("Falkland Islands (Malvinas)"),
	_T("239"),_T("South Georgia and the South Sandwich Islands"),
	_T("242"),_T("Fiji, Republic of the Fiji Islands"),
	_T("246"),_T("Finland, Republic of"),
	_T("250"),_T("France, French Republic"),
	_T("254"),_T("French Guiana"),
	_T("258"),_T("French Polynesia"),
	_T("260"),_T("French Southern Territories"),
	_T("262"),_T("Djibouti, Republic of"),
	_T("266"),_T("Gabon, Gabonese Republic"),
	_T("268"),_T("Georgia"),
	_T("270"),_T("Gambia, Republic of the"),
	_T("275"),_T("Palestinian Territory, Occupied"),
	_T("276"),_T("Germany"),
	_T("288"),_T("Ghana, Republic of"),
	_T("292"),_T("Gibraltar"),
	_T("296"),_T("Kiribati, Republic of"),
	_T("300"),_T("Greece, Hellenic Republic"),
	_T("304"),_T("Greenland"),
	_T("308"),_T("Grenada"),
	_T("312"),_T("Guadaloupe"),
	_T("316"),_T("Guam"),
	_T("320"),_T("Guatemala, Republic of"),
	_T("324"),_T("Guinea, Revolutionary People's Rep'c of"),
	_T("328"),_T("Guyana, Republic of"),
	_T("332"),_T("Haiti, Republic of"),
	_T("334"),_T("Heard and McDonald Islands"),
	_T("336"),_T("Holy See (Vatican City State)"),
	_T("340"),_T("Honduras, Republic of"),
	_T("344"),_T("Hong Kong, Special Administrative Region of China"),
	_T("348"),_T("Hungary, Hungarian People's Republic"),
	_T("352"),_T("Iceland, Republic of"),
	_T("356"),_T("India, Republic of"),
	_T("360"),_T("Indonesia, Republic of"),
	_T("364"),_T("Iran, Islamic Republic of"),
	_T("368"),_T("Iraq, Republic of"),
	_T("372"),_T("Ireland"),
	_T("376"),_T("Israel, State of"),
	_T("380"),_T("Italy, Italian Republic"),
	_T("384"),_T("Cote D'Ivoire, Ivory Coast, Republic of the"),
	_T("388"),_T("Jamaica"),
	_T("392"),_T("Japan"),
	_T("398"),_T("Kazakhstan, Republic of"),
	_T("400"),_T("Jordan, Hashemite Kingdom of"),
	_T("404"),_T("Kenya, Republic of"),
	_T("408"),_T("Korea, Democratic People's Republic of"),
	_T("410"),_T("Korea, Republic of"),
	_T("414"),_T("Kuwait, State of"),
	_T("417"),_T("Kyrgyz Republic"),
	_T("418"),_T("Lao People's Democratic Republic"),
	_T("422"),_T("Lebanon, Lebanese Republic"),
	_T("426"),_T("Lesotho, Kingdom of"),
	_T("428"),_T("Latvia"),
	_T("430"),_T("Liberia, Republic of"),
	_T("434"),_T("Libyan Arab Jamahiriya"),
	_T("438"),_T("Liechtenstein, Principality of"),
	_T("440"),_T("Lithuania"),
	_T("442"),_T("Luxembourg, Grand Duchy of"),
	_T("446"),_T("Macao, Special Administrative Region of China"),
	_T("450"),_T("Madagascar, Republic of"),
	_T("454"),_T("Malawi, Republic of"),
	_T("458"),_T("Malaysia"),
	_T("462"),_T("Maldives, Republic of"),
	_T("466"),_T("Mali, Republic of"),
	_T("470"),_T("Malta, Republic of"),
	_T("474"),_T("Martinique"),
	_T("478"),_T("Mauritania, Islamic Republic of"),
	_T("480"),_T("Mauritius"),
	_T("484"),_T("Mexico, United Mexican States"),
	_T("492"),_T("Monaco, Principality of"),
	_T("496"),_T("Mongolia, Mongolian People's Republic"),
	_T("498"),_T("Moldova, Republic of"),
	_T("500"),_T("Montserrat"),
	_T("504"),_T("Morocco, Kingdom of"),
	_T("508"),_T("Mozambique, People's Republic of"),
	_T("512"),_T("Oman, Sultanate of"),
	_T("516"),_T("Namibia"),
	_T("520"),_T("Nauru, Republic of"),
	_T("524"),_T("Nepal, Kingdom of"),
	_T("528"),_T("Netherlands, Kingdom of the"),
	_T("530"),_T("Netherlands Antilles"),
	_T("533"),_T("Aruba"),
	_T("540"),_T("New Caledonia"),
	_T("548"),_T("Vanuatu"),
	_T("554"),_T("New Zealand"),
	_T("558"),_T("Nicaragua, Republic of"),
	_T("562"),_T("Niger, Republic of the"),
	_T("566"),_T("Nigeria, Federal Republic of"),
	_T("570"),_T("Niue, Republic of"),
	_T("574"),_T("Norfolk Island"),
	_T("578"),_T("Norway, Kingdom of"),
	_T("580"),_T("Northern Mariana Islands"),
	_T("581"),_T("United States Minor Outlying Islands"),
	_T("583"),_T("Micronesia, Federated States of"),
	_T("584"),_T("Marshall Islands"),
	_T("585"),_T("Palau"),
	_T("586"),_T("Pakistan, Islamic Republic of"),
	_T("591"),_T("Panama, Republic of"),
	_T("598"),_T("Papua New Guinea"),
	_T("600"),_T("Paraguay, Republic of"),
	_T("604"),_T("Peru, Republic of"),
	_T("608"),_T("Philippines, Republic of the"),
	_T("612"),_T("Pitcairn Island"),
	_T("616"),_T("Poland, Polish People's Republic"),
	_T("620"),_T("Portugal, Portuguese Republic"),
	_T("624"),_T("Guinea-Bissau, Republic of"),
	_T("626"),_T("Timor-Leste, Democratic Republic of"),
	_T("630"),_T("Puerto Rico"),
	_T("634"),_T("Qatar, State of"),
	_T("638"),_T("Reunion"),
	_T("642"),_T("Romania, Socialist Republic of"),
	_T("643"),_T("Russian Federation"),
	_T("646"),_T("Rwanda, Rwandese Republic"),
	_T("654"),_T("St. Helena"),
	_T("659"),_T("St. Kitts and Nevis"),
	_T("660"),_T("Anguilla"),
	_T("662"),_T("St. Lucia"),
	_T("666"),_T("St. Pierre and Miquelon"),
	_T("670"),_T("St. Vincent and the Grenadines"),
	_T("674"),_T("San Marino, Republic of"),
	_T("678"),_T("Sao Tome and Principe, Democratic Republic of"),
	_T("682"),_T("Saudi Arabia, Kingdom of"),
	_T("686"),_T("Senegal, Republic of"),
	_T("690"),_T("Seychelles, Republic of"),
	_T("694"),_T("Sierra Leone, Republic of"),
	_T("702"),_T("Singapore, Republic of"),
	_T("703"),_T("Slovakia (Slovak Republic)"),
	_T("704"),_T("Viet Nam, Socialist Republic of"),
	_T("705"),_T("Slovenia"),
	_T("706"),_T("Somalia, Somali Republic"),
	_T("710"),_T("South Africa, Republic of"),
	_T("716"),_T("Zimbabwe"),
	_T("724"),_T("Spain, Spanish State"),
	_T("732"),_T("Western Sahara"),
	_T("736"),_T("Sudan, Democratic Republic of the"),
	_T("740"),_T("Suriname, Republic of"),
	_T("744"),_T("Svalbard & Jan Mayen Islands"),
	_T("748"),_T("Swaziland, Kingdom of"),
	_T("752"),_T("Sweden, Kingdom of"),
	_T("756"),_T("Switzerland, Swiss Confederation"),
	_T("760"),_T("Syrian Arab Republic"),
	_T("762"),_T("Tajikistan"),
	_T("764"),_T("Thailand, Kingdom of"),
	_T("768"),_T("Togo, Togolese Republic"),
	_T("772"),_T("Tokelau (Tokelau Islands)"),
	_T("776"),_T("Tonga, Kingdom of"),
	_T("780"),_T("Trinidad and Tobago, Republic of"),
	_T("784"),_T("United Arab Emirates"),
	_T("788"),_T("Tunisia, Republic of"),
	_T("792"),_T("Turkey, Republic of"),
	_T("795"),_T("Turkmenistan"),
	_T("796"),_T("Turks and Caicos Islands"),
	_T("798"),_T("Tuvalu"),
	_T("800"),_T("Uganda, Republic of"),
	_T("804"),_T("Ukraine"),
	_T("807"),_T("Macedonia, the former Yugoslav Republic of"),
	_T("818"),_T("Egypt, Arab Republic of"),
	_T("826"),_T("United Kingdom of Great Britain & N. Ireland"),
	_T("834"),_T("Tanzania, United Republic of"),
	_T("840"),_T("United States of America"),
	_T("850"),_T("US Virgin Islands"),
	_T("854"),_T("Burkina Faso"),
	_T("858"),_T("Uruguay, Eastern Republic of"),
	_T("860"),_T("Uzbekistan"),
	_T("862"),_T("Venezuela, Bolivarian Republic of"),
	_T("876"),_T("Wallis and Futuna Islands"),
	_T("882"),_T("Samoa, Independent State of"),
	_T("887"),_T("Yemen"),
	_T("891"),_T("Serbia and Montenegro"),
	_T("894"),_T("Zambia, Republic of"),
	0
};