#include "stdafx.h"
#include "tagList.h"

const char *tagList[][2] = {
	{"5A" ,		"Primary Account Number (PAN)"},
	{"92" ,		"Issuer Public Key Remainder"},
	{"86" ,		"Isuer Script Command"},
	{"9F18" ,	"Issuer Script Identifier"},
	{"71" ,		"Issuer Script Template 1"},
	{"72" ,		"Issuer Script Template 2"},
	{"5F2D" ,	"Language Preference"},
	{"9F13" ,	"Last Online ATC Register"},
	{"9F14" ,	"Lower Consecutive Offline Limit (EMV Generic)"},
	{"9F58" ,	"Lower Consecutive Offline Limit (Proprietary)"},
	{"9F15" ,	"Merchant Category Code"},
	{"9F16" ,	"Merchant Identifier"},
	{"9F17" ,	"PIN Try Counter"},
	{"9F39" ,	"POS Entry Mode"},
	{"9F38" ,	"Processing Options Data Object List (PDOL)"},
	{"80" ,		"Response Message Template Format 1"},
	{"77" ,		"Response Message Template Format 2"},
	{"83" ,		"Command Template"},
	{"4F" ,		"Application Identifier"},
	{"82" ,		"Application Interchange Profile"},
	{"94" ,		"Application File Locator (AFL)"},
	{"9F76" ,	"Secondary Apllication Currency Code"},
	{"5F30" ,	"Service Code"},
	{"88" ,		"Short File Identifier (SFI)"},
	{"89" ,		"Authorisation Code"},
	{"9F4B" ,	"Signed Dynamic Application Data"},
	{"93" ,		"Signed Application Data"},
	{"9F4A" ,	"Static Data Authentication Tag List"},
	{"9F33" ,	"Terminal Capabilities"},
	{"9F1A" ,	"Terminal Country Code"},
	{"9F1B" ,	"Terminal Floor Limit"},
	{"9F1C" ,	"Terminal Identification"},
	{"9F1D" ,	"Terminal Risk Management Data"},
	{"9F35" ,	"Terminal Type"},
	{"95" ,		"Terminal Verification Results"},
	{"9F1F" ,	"Track 1 Discretion Data"},
	{"9F20" ,	"Track 2 Discretion Data"},
	{"57" ,		"Track 2 Equivalent Data"},
	{"97" ,		"Transaction Certificate Data Object List (TDOL)"},
	{"98" ,		"Transaction Certificate (TC) Hash Value"},
	{"5F2A" ,	"Transaction Currency Code"},
	{"5F36" ,	"Transaction Currency Exponent"},
	{"9A" ,		"Transaction Date"},
	{"99" ,		"Transaction PIN Data"},
	{"9F3C" ,	"Transaction Reference Currency Code"},
	{"9F3D" ,	"Transaction Reference Currency Exponent"},
	{"9F41" ,	"Transaction Status Counter"},
	{"9B" ,		"Transaction Status Information"},
	{"9F21" ,	"Transaction Time"},
	{"9C" ,		"Transaction Type"},
	{"9F37" ,	"Unpredictable Number"},
	{"9F23" ,	"Upper Consecutive Offline Limit (EMV Generic)"},
	{"9F59" ,	"Upper Consecutive Offline Limit (Proprietary)"},
	{"9F01" ,	"Acquirer Identifier"},
	{"9F40" ,	"Additional Terminal Capabilities"},
	{"81" ,		"Amount, Authorised (Binary)"},
	{"9F02" ,	"Amount, Authorized (Numeric)"},
	{"9F04" ,	"Amount, Other (Binary)"},
	{"9F03" ,	"Amount, Other (Numeric)"},
	{"9F3A" ,	"Amount,Reference Currency"},
	{"9F26" ,	"Application Cryptogram (AC)"},
	{"9F42" ,	"Application Currency Code"},
	{"9F44" ,	"Application Currency Exponent"},
	{"9F52" ,	"Application Default Action"},
	{"9F05" ,	"Application Discretionary Data"},
	{"5F25" ,	"Application Effective Date"},
	{"70" ,		"Application Elementary File (AEF) Data Template"},
	{"5F24" ,	"Application Expiration Date"},
	{"9F06" ,	"Application Identifier (AID) (Terminal)"},
	{"50" ,		"Application Label"},
	{"9F12" ,	"Application Preferred Name"},
	{"5A" ,		"Application Primary Account Number (PAN)"},
	{"5F34" ,	"Application PAN Sequence Number"},
	{"87" ,		"Application Priority Indicator"},
	{"9F3B" ,	"Application Reference Currency"},
	{"9F43" ,	"Application Reference Currency Exponent"},
	{"61" ,		"Application Template"},
	{"9F36" ,	"Application Transaction Counter (ATC)"},
	{"9F07" ,	"Application Usage Control"},
	{"9F08" ,	"Application Version Number"},
	{"9F09" ,	"Application Version Number (Terminal)"},
	{"8A" ,		"Authorisation Response Code"},
	{"9F7F" ,	"Card Product Life Cycle History File Identifiers"},
	{"8C" ,		"Card Risk Management Data 1 (CDOL1)"},
	{"8D" ,		"Card Risk Management Data 2 (CDOL2)"},
	{"5F20" ,	"Cardholder Name"},
	{"9F0B" ,	"Cardholder Name Extended"},
	{"8E" ,		"Cardholder Verification Method (CVM) List"},
	{"9F34" ,	"Cardholder Verification Method (CVM) Results"},
	{"8F" ,		"Certification Authority Public Key Index"},
	{"9F22" ,	"Certification Authority Public Key Index"},
	{"52" ,		"Command To Perform"},
	{"9F72" ,	"Consecutive Transaction Limit (international - country)"},
	{"9F27" ,	"Cryptogram Information Data (CID)"},
	{"9F75" ,	"Cumulative Total Transaction Amount Limit - Dual Currency"},
	{"9F73" ,	"Currency Conversion Factor"},
	{"9F45" ,	"Data Authentication Code"},
	{"84" ,		"Dedicated File (DF) Name"},
	{"9D" ,		"Directory Definition File (DDF) Name"},
	{"73" ,		"Directory Discretionary Template"},
	{"9F49" ,	"Dynamic Data Authentication Data (DDOL)"},
	{"BF0C" ,	"FCI Discretionary Data"},
	{"A5" ,		"FCI Proprietary Template"},
	{"6F" ,		"FCI Template"},
	{"9F4C" ,	"ICC Dynamic Number"},
	{"9F2D" ,	"ICC PIN Encipherment Public Key Certificate"},
	{"9F2E" ,	"ICC PIN Encipherment Public Key Exponent"},
	{"9F2F" ,	"ICC PIN Encipherment Public Key Remainder"},
	{"9F46" ,	"ICC Public Key Certificate"},
	{"9F47" ,	"ICC Public Key Exponent"},
	{"9F48" ,	"ICC Public Key Remainder"},
	{"9F1E" ,	"Interface Device Serial Number"},
	{"9F0D" ,	"Issuer Action Code - Default"},
	{"9F0E" ,	"Issuer Action Code - Denial"},
	{"9F0F" ,	"Issuer Action Code - Online"},
	{"9F10" ,	"Issuer Application Data"},
	{"91" ,		"Issuer Authentication Data"},
	{"9F11" ,	"Issuer Code Table Index"},
	{"5F28" ,	"Issuer Country Code"},
	{"90" ,		"Issuer Public Key Certificate"},
	{"9F32" ,	"Issuer Public Key Exponent"},
	{"9F4D" ,	"Log Entry"},
	{"9F4E" ,	"Merchant Name and Location"},
	{"9F4F" ,	"Log Format"},
	{"5F50" ,	"Issuer URL"},
	{"5F53" ,	"International Bank Account Number (IBAN)"},
	{"5F54" ,	"Bank Identifier Code (BIC)"},
	{"5F55" ,	"Issuer Country Code (alpha2 format)"},
	{"5F56" ,	"Issuer Country Code (alpha3 format) "},
	{"42" ,		"Issuer Identification Number (IIN)"},
	{0,0}
 };